# Generated by Django 2.0.2 on 2025-03-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleBookStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
